---
title: "Visualization with section"
output: md_notebook
---
## 

```{r}
rm(list = ls())
library(ggplot2)
library(gridExtra)
library(dplyr)
library(reshape2)
source("functions.R")
source("visFunctions.R")
```

## load data
```{r}

data <- read.csv("https://raw.githubusercontent.com/sun-binrwei/ondiversity/update/python_note/output.csv")

# names(data)
```

## prepare the data of interest
(e.g. now we want to see the diversity within each "study group" of a particular "section")

```{r}
# assign a section
s <- 1 # section 1

# section data (preserve only columns with information of interest)
secdata <- data[data$Section == s,
                c("Gender", "Primary.Nat", "Last.Job.Domain.Description") ]
                # e.g. we are interested in the diversity in these 3 things
# safe the "study group" assignment in another variable (data.frame)
secgroup <- data[data$Section == s, "Study.Group"]

# take a look at the data
head(secdata, 3)
```
```{r}
secgroup
```


```{r}
nicknames <- c("Gender", "Nat", "Job")
# use the `tabDiversity` function (in visFunctions.R) to tabulate the diversity index
dfout <- tabDiversity(secdata, secgroup, nicknames)
#head(dfout)
tail(dfout)
```

## plot

```{r}
#v <- 1
p1 <- ggplot(dfout[dfout$variable == "IER",], aes(x = Group, y = value, fill = Scale))
p1 <- p1 + geom_bar(stat = "identity")
p1 <- p1 + facet_grid(Type ~ ., scales = "free")
p1 <- p1 +  theme(legend.position="none")
p1 <- p1 +   labs(title="IER")

p2 <- ggplot(dfout[dfout$variable == "Richness",], aes(x = Group, y = value, fill = Scale))
p2 <- p2 + geom_bar(stat = "identity")
p2 <- p2 + facet_grid(Type~ ., scales = "free")
p2 <- p2 +  theme(legend.position="none")
p2 <- p2 +   labs(title="Richness")


grid.arrange(p2,p1,  ncol=2)
```

```{r}
grdata <- data[,  c("Gender", "Primary.Nat", "Last.Job.Domain.Description")]
grgroup <- data$Section
dfoutClass <- tabDiversity(grdata, grgroup, nicknames)
head(dfoutClass,3)
```

```{r}
p1 <- ggplot(dfoutClass[dfoutClass$variable == "IER",], aes(x = Group, y = value, fill = Scale))
p1 <- p1 + geom_bar(stat = "identity")
p1 <- p1 + facet_grid(Type ~ ., scales = "free")
p1 <- p1 +  theme(legend.position="none")
p1 <- p1 +   labs(title="IER")


p2 <- ggplot(dfoutClass[dfoutClass$variable == "Richness",], aes(x = Group, y = value, fill = Scale))
p2 <- p2 + geom_bar(stat = "identity")
p2 <- p2 + facet_grid(Type~ ., scales = "free")
p2 <- p2 +  theme(legend.position="none")
p2 <- p2 +   labs(title="Richness")


grid.arrange(p2,p1,  ncol=2)
```

